### ISSUE TITLE
Add minimal theme custom checkboxes support

### ISSUE THREAD

**Issue by oyes77** [KeithLerner/ObsidianMDsQdthOne#14]
it's a standard I have found in multiple themes and i have accustomed into using them in my workflow:

Basic checklists:

- [x] to-do
- [/] incomplete
- [x] done
- [-] canceled
- [>] forwarded
- [<] scheduling

Extras checklists:

- [?] question
- [!] important
- [*] star
- ["] quote
- [l] location
- [b] bookmark
- [i] information
- [S] savings
- [I] idea
- [p] pros
- [c] cons
- [f] fire
- [k] key
- [w] win
- [u] up
- [d] down

**Comment by KeithLerner** [comment]
Thank you for the suggestion, I will make sure this feature is added to the next version update! Aiming to release the update at the end of January.

**Comment by KeithLerner** [comment]
I will manually resolve this issue as closed once the feature is implemented.

**Comment by KeithLerner** [comment]
This feature is going to be delayed a bit, packaging it with other new changes before release. It is available now in the dev branch along with the other changes it will be released alongside.
