### ISSUE TITLE
Hi! Friends, this theme needs to improve ......

### ISSUE THREAD

**Issue by zhouxinghong** [KeithLerner/ObsidianMDsQdthOne#16]
Hi! friend,
1. This theme needs to improve the background color and foreground color support of python code blocks.
![image](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/abc5d1f2-7419-4c9f-b25e-60c81b8ea585)

2. The background color of selected text content needs to be improved.
![image](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/34227409-62c3-4bf0-975f-6b4630397a5f)

Windows 10
Obsidian 1.5.8
Thank you so much for an excellent theme! 👍🎉

**Comment by KeithLerner** [comment]
Hi!

Thank you for your comment, I will get this fixed as soon as I can!

I will close this issue upon completion.

**Comment by KeithLerner** [comment]
Are you using the solar variant?

**Comment by zhouxinghong** [comment]
Yes! But the default and colorless also have the same problem

**Comment by KeithLerner** [comment]
Thank you for your patience, I've made changes. I had to change some of the colors both for clarity and to better align my theme with solarized themes for other IDEs and software.
