### ISSUE TITLE
Hi! Friends, thank you for a very beautiful theme

### ISSUE THREAD

**Issue by zhouxinghong** [KeithLerner/ObsidianMDsQdthOne#18]
Hi! Friends, thank you for a very beautiful theme

1. During my use, I found that the background color, foreground color, and border color of the update prompt information need to be improved;
![2024-02-26_ddddddddddd](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/0b91a537-baf8-4b58-8a1c-03718d972f66)

2. The background color, foreground color, and border color of the statistics panel in the lower right corner need to be improved;
![2024-02-26_1fffffffffffff](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/bc950ae4-fe33-4bde-8a88-d2677f9f7859)

3. The background color, foreground color, and border color of the right-click menu need to be improved!
![image](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/e8b7f91a-c544-40ee-b8e6-e81feb6aaf9e)

friend! Thanks again for a very beautiful theme. 🎉👍
windows 10
1.5.8

**Comment by KeithLerner** [comment]
Sorry this has taken so long to get to my friend, making these changes now. Will close this issue once fixed
