### ISSUE TITLE
friend! Your theme is great👍 hope the border colors can be improved further

### ISSUE THREAD

**Issue by zhouxinghong** [KeithLerner/ObsidianMDsQdthOne#20]
friend! Your theme is great👍 hope the border colors can be improved further
![image](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/584ae2d2-4843-48ea-a23f-d6a44129aa92)
![image](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/4efe306e-fe89-416a-87c8-595e35aee004)
![image](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/34a707a5-22f4-4052-968f-ee9d4c4c2d99)

The following is an example of a screenshot of the theme border in Dark mode. The theme border color also needs to be improved in Light mode. . .

Thank you very much again for a very excellent topic. 🎉👏😜
Windows 19044
1.5.8

**Comment by KeithLerner** [comment]
The border of dropdown options within the main settings menu can not be changed with CSS from what I can tell. The other border-related issues are fixed with the latest version of the theme!

**Comment by zhouxinghong** [comment]
![image](https://github.com/KeithLerner/ObsidianMDsQdthOne/assets/54253524/e7a90b6e-e0bb-480c-9ed3-75799bcce1bd)
The borders are too thick and the colors don't match the theme.

**Comment by KeithLerner** [comment]
Updated to match other menu borders 😎
